function Result = readCsv(obj, FileName )
Result ='';
FileNameSQL = strrep(FileName, '\', '\\');
fid = fopen(FileName);
Header =  regexp(fgetl(fid),'\w*', 'match');
Header = [Header(1:6) 'time_id'];
fclose(fid);

Types = {'VARCHAR(15)' 'VARCHAR(50)'...
    'FLOAT' 'INT' 'DATETIME(3)' 'INT' 'CHAR(14)'};

TableHeader = cellfun(@(x, y)...
    [ x ' ' y ' NOT NULL,'],Header, Types,...
    'UniformOutput', false);
TableHeader = [TableHeader{:}];
exec(obj.Connection,...
    ' SET max_heap_table_size = 1024*1024*512');

exec(obj.Connection,[...
    ' DROP TEMPORARY TABLE IF EXISTS'...
    ' temp_table'...
    ]);

%Create temporary table in database
exec(obj.Connection,[...
    ' CREATE TEMPORARY TABLE'...
    ' temp_table('...
    TableHeader ...
    ' INDEX (code))' ...
    ' ENGINE = MEMORY'...
    ]);

%Load data from *.csv file to temporary table
exec(obj.Connection, [...
    ' LOAD DATA LOCAL INFILE '''...
    FileNameSQL ''''...
    ' INTO TABLE temp_table'...
    ' COLUMNS TERMINATED BY '';'''...
    ' LINES TERMINATED BY ''\r\n'''...
    ' IGNORE 1 LINES'...
    ]);

%Delete out of marked trades (Nosystem = 1)
exec(obj.Connection, [...
    ' DELETE'...
    ' FROM temp_table WHERE time_id = "1"'...
    ]);

%Rewrite Nosystem column with time_id data
exec(obj.Connection, [...
    ' UPDATE temp_table'...
    ' SET time_id ='...
    ' DATE_FORMAT(dat_time, ''%Y%m%d%k%i%s'')'...
    ]);

TableNames = fetch(obj.Connection, [...
    ' SELECT DISTINCT code, contract'...
    ' FROM temp_table'...
    ]);

%Remove empty elements
CodeIndexes = cellfun(@(x)...
    ~isempty(x), TableNames(:,1));
TableNames =  TableNames(CodeIndexes,:);

% Replace all dots in code names with '_'
TableNames(:,1) = strrep(TableNames(:,1), '.','_');

Header = Header([3:4 6:7]);
HeaderString = cell2mat( regexp( ...
    sprintf(',%s', Header{:}), '^,', 'split' ));
Types = Types([3:4 6:7]);
TableHeader = cellfun(@(x, y)...
    [ x ' ' y ' NOT NULL,'], Header, Types,...
    'UniformOutput', false);
TableHeader = [TableHeader{:}];
assignin('base', 'TableNames', TableNames);
for i=1:size(TableNames, 1)
    %          exec(obj.Connection, [...
    %            ' DROP TABLE IF EXISTS '...
    %            TableNames{i,1}...
    %            ]);
    
    exec(obj.Connection, [...
        ' CREATE TABLE IF NOT EXISTS '...
        '`' TableNames{i,2} '` ('...
        TableHeader...
        ' PRIMARY KEY (trade_id),'...
        ' INDEX seconds (time_id)'...
        ')'...
        ' ENGINE = MyISAM'...
        ' DEFAULT CHARSET=utf8'...
        ' COLLATE utf8_bin'...
        ' COMMENT ''tick_table'''...
        ]);
    
    Res = exec(obj.Connection, [...
        ' INSERT INTO ' ...
        '`' TableNames{i,2} '` ('...
        HeaderString ')'...
        ' SELECT '  HeaderString...
        ' FROM temp_table'...
        ' WHERE code = '''...
        strrep(TableNames{i,1},'_','.') ''''...
        ' ORDER BY trade_id'...
        ' ON DUPLICATE KEY UPDATE'...
        ' trade_id = VALUES(trade_id)'...
        ]);
    if ~isempty(Res.message)
        Result = Res.message;
    end
end

exec(obj.Connection,[...
    ' DROP TEMPORARY TABLE IF EXISTS'...
    ' temp_table'...
    ]);

end
